name: qubo_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
#  - jupyter
  - ca-certificates
  - openssl
#  - qiskit=1.1
#  - pylatexenc
  - certifi
#  - autograd
#  - cvxpy
  - dimod
  - regex
#  - cupy
   - pip:
     - genosolver
     - gurobypy
     - gurobi-optimods