name: qubo_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pyyaml
  - regex
  - networkx
  - pip:
    - genosolver
    - gurobipy
    - gurobi-optimods
    - dwave-system
    - dimod